# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='addBy',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='analyst',
            old_name='addBy',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='addBy',
            new_name='person',
        ),
    ]
