# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20180201_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', unique=True, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='analyst',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', unique=True, verbose_name='Измеритель'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', unique=True, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь'),
        ),
    ]
