# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_auto_20180301_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Измеритель'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Заказчик'),
        ),
    ]
