# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0014_auto_20180301_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('verifyed', models.BooleanField(default=False, verbose_name='Данные введены ии проверены')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst', to='persons.Analyst', verbose_name='Исполнитель')),
                ('appointedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointedBy', to='persons.Analyst', verbose_name='Назначен')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
        migrations.CreateModel(
            name='AnalyzeDataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Наименование формата')),
                ('enable', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'AnalyzeDataFormat',
                'verbose_name_plural': 'AnalyzeDataFormats',
            },
        ),
        migrations.CreateModel(
            name='AnalyzeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид анализов',
                'verbose_name_plural': 'Виды анализов',
            },
        ),
        migrations.CreateModel(
            name='DataBinaryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода')),
                ('value', models.BinaryField()),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ')),
            ],
            options={
                'verbose_name': 'dataBinaryValue',
                'verbose_name_plural': 'dataBinaryValues',
            },
        ),
        migrations.CreateModel(
            name='DataFormatField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(blank=True, max_length=100, verbose_name='Имя поля')),
                ('fieldType', models.CharField(blank=True, choices=[('int', 'Число'), ('text', 'Текст'), ('img', 'Картинка'), ('xls', 'Файл XLS'), ('bin', 'Двоичный файл')], default=int, max_length=100, verbose_name='Тип данных в поле')),
                ('serialNumber', models.IntegerField(verbose_name='Код поля')),
                ('optional', models.BooleanField(verbose_name='Обязательность заполнения')),
                ('fieldCaption', models.CharField(blank=True, max_length=100, verbose_name='Заголовок поля')),
                ('fieldWidth', models.IntegerField(verbose_name='Ширина поля')),
                ('fieldWidthInTable', models.IntegerField(verbose_name='Ширина поля в таблице')),
                ('dataFormat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.AnalyzeDataFormat', verbose_name='Формат данных')),
            ],
            options={
                'verbose_name': 'DataFormatField',
                'verbose_name_plural': 'DataFormatFields',
            },
        ),
        migrations.CreateModel(
            name='DataImageValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода')),
                ('value', models.ImageField(upload_to='', verbose_name='Значение')),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ')),
                ('dataFormatField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных')),
            ],
            options={
                'verbose_name': 'dataImageValue',
                'verbose_name_plural': 'dataImageValues',
            },
        ),
        migrations.CreateModel(
            name='dataIntValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Значение')),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ')),
                ('dataFormatField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных')),
            ],
            options={
                'verbose_name': 'dataIntValue',
                'verbose_name_plural': 'dataIntValues',
            },
        ),
        migrations.CreateModel(
            name='DataTextValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода')),
                ('value', models.TextField(verbose_name='Значение')),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ')),
                ('dataFormatField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных')),
            ],
            options={
                'verbose_name': 'dataTextValue',
                'verbose_name_plural': 'dataTextValues',
            },
        ),
        migrations.CreateModel(
            name='DataXLSValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода')),
                ('value', models.FileField(upload_to='')),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ')),
                ('dataFormatField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных')),
            ],
            options={
                'verbose_name': 'dataXLSValue',
                'verbose_name_plural': 'dataXLSValues',
            },
        ),
        migrations.CreateModel(
            name='DeliverySample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Доставка образца',
                'verbose_name_plural': 'Доставки образцов',
            },
        ),
        migrations.CreateModel(
            name='GroupAnalyzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа анализов',
                'verbose_name_plural': 'Группы анализов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код заявки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('executed', models.BooleanField(default=False, verbose_name='Анализ сделан и данные введены')),
                ('executedDateTime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='OrdersCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код заявки')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код образца')),
                ('status', models.BooleanField(default=False, verbose_name='Образец получен лабораторией')),
                ('comment', models.TextField(blank=True, verbose_name='Описание образца')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Опытный образец',
                'verbose_name_plural': 'Опытные образцы',
            },
        ),
        migrations.CreateModel(
            name='SamplesCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeOfSample', models.CharField(max_length=20, unique=True, verbose_name='Код образца')),
            ],
        ),
        migrations.CreateModel(
            name='SetAnalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Analyst')),
                ('assignBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst', to='analyzes.Order')),
            ],
            options={
                'verbose_name': 'Назначение измерителя',
                'verbose_name_plural': 'Назначения измерителя',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='codeOfSample',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordersam', to='analyzes.Sample', verbose_name='Код образца'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Customer', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.AnalyzeType', verbose_name='Тип анализа'),
        ),
        migrations.AddField(
            model_name='deliverysample',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Order'),
        ),
        migrations.AddField(
            model_name='databinaryvalue',
            name='dataFormatField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных'),
        ),
        migrations.AddField(
            model_name='analyzetype',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analyzes.GroupAnalyzes'),
        ),
        migrations.AddField(
            model_name='analyzedataformat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.AnalyzeType', verbose_name='Тип анализа'),
        ),
        migrations.AddField(
            model_name='analyze',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Order', verbose_name='Заявка'),
        ),
    ]
