# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20180301_0934'),
        ('analyzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzetype',
            name='defaultanalyst',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Analyst'),
        ),
    ]
