# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzetype',
            name='name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
