# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0002_analyzetype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzetype',
            options={'verbose_name': 'AnalyzeType', 'verbose_name_plural': 'AnalyzeTypes'},
        ),
    ]
