# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0003_auto_20180120_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzetype',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
