# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0004_auto_20180129_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzetype',
            name='code',
            field=models.CharField(default='xxx', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
