# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 09:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0005_analyzetype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst', to='persons.Analyst', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='appointedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointedBy', to='persons.Analyst', verbose_name='Назначен'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Order', unique=True, verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='verifyed',
            field=models.BooleanField(default=False, verbose_name='Данные введены ии проверены'),
        ),
        migrations.AlterField(
            model_name='analyzedataformat',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='analyzetype',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='analyzetype',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='codeOfSample',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
