# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0006_auto_20180201_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyze',
            options={'verbose_name': 'Анализ', 'verbose_name_plural': 'Анализы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='analyzedataformat',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='analyzedataformat',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Наименование формата'),
        ),
        migrations.AlterField(
            model_name='analyzedataformat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.AnalyzeType', verbose_name='Тип анализа'),
        ),
        migrations.AlterField(
            model_name='databinaryvalue',
            name='analyze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='databinaryvalue',
            name='dataFormatField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных'),
        ),
        migrations.AlterField(
            model_name='databinaryvalue',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='fieldCaption',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок поля'),
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='fieldName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя поля'),
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='fieldType',
            field=models.CharField(blank=True, choices=[('int', 'Число'), ('text', 'Текст'), ('img', 'Картинка'), ('xls', 'Файл XLS'), ('bin', 'Двоичный файл')], default=int, max_length=100, verbose_name='Тип данных в поле'),
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='fieldWidth',
            field=models.IntegerField(verbose_name='Ширина поля'),
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='fieldWidthInTable',
            field=models.IntegerField(verbose_name='Ширина поля в таблице'),
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='optional',
            field=models.BooleanField(verbose_name='Обязательность заполнения'),
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='serialNumber',
            field=models.IntegerField(verbose_name='Код поля'),
        ),
        migrations.AlterField(
            model_name='dataimagevalue',
            name='analyze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='dataimagevalue',
            name='dataFormatField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных'),
        ),
        migrations.AlterField(
            model_name='dataimagevalue',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='dataimagevalue',
            name='value',
            field=models.ImageField(upload_to='', verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='dataintvalue',
            name='analyze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='dataintvalue',
            name='dataFormatField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных'),
        ),
        migrations.AlterField(
            model_name='dataintvalue',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='dataintvalue',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='datatextvalue',
            name='analyze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='datatextvalue',
            name='dataFormatField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных'),
        ),
        migrations.AlterField(
            model_name='datatextvalue',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='datatextvalue',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='dataxlsvalue',
            name='analyze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Analyze', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='dataxlsvalue',
            name='dataFormatField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormatField', verbose_name='Шаблон ввода данных'),
        ),
        migrations.AlterField(
            model_name='dataxlsvalue',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата ввода'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Код заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='codeOfSample',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Код образца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='Анализ сделан и данные введены'),
        ),
    ]
