# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0007_auto_20180201_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код заявки')),
            ],
        ),
        migrations.CreateModel(
            name='SamplesCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeOfSample', models.CharField(max_length=20, unique=True, verbose_name='Код образца')),
            ],
        ),
        migrations.AlterField(
            model_name='analyze',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='codeOfSample',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код образца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.AnalyzeType', verbose_name='Тип анализа'),
        ),
    ]
