# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0010_auto_20180202_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Формат активен')),
                ('atype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.AnalyzeType', verbose_name='Тип анализа')),
            ],
        ),
        migrations.AddField(
            model_name='dataformatfield',
            name='dataFormat',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='analyzes.DataFormat', verbose_name='Формат данных'),
        ),
    ]
