# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0012_auto_20180204_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataformat',
            name='atype',
        ),
        migrations.AlterField(
            model_name='dataformatfield',
            name='dataFormat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.AnalyzeDataFormat', verbose_name='Формат данных'),
        ),
        migrations.DeleteModel(
            name='DataFormat',
        ),
    ]
