# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_auto_20180202_0107'),
        ('analyzes', '0013_auto_20180204_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Order', unique=True)),
            ],
            options={
                'verbose_name': 'Доставка образца',
                'verbose_name_plural': 'Доставки образцов',
            },
        ),
        migrations.CreateModel(
            name='SetAnalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Analyst')),
                ('assignBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Order', unique=True)),
            ],
            options={
                'verbose_name': 'Назначение измерителя',
                'verbose_name_plural': 'Назначения измерителя',
            },
        ),
    ]
