# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0016_auto_20180208_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAnalyzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа анализов',
                'verbose_name_plural': 'Группы анализов',
            },
        ),
        migrations.AlterModelOptions(
            name='analyzetype',
            options={'verbose_name': 'Вид анализов', 'verbose_name_plural': 'Виды анализов'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Опытный образец', 'verbose_name_plural': 'Опытные образцы'},
        ),
        migrations.AlterField(
            model_name='analyze',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Описание образца'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Образец получен лабораторией'),
        ),
        migrations.AddField(
            model_name='analyzetype',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='analyzes.GroupAnalyzes'),
        ),
    ]
