# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0018_remove_analyzetype_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupAnalyzes',
        ),
    ]
