# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0019_delete_groupanalyzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAnalyzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Группы анализов',
                'verbose_name': 'Группа анализов',
            },
        ),
    ]
