# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0021_analyzetype_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzetype',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analyzes.GroupAnalyzes'),
        ),
    ]
