# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0022_auto_20180215_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysample',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzes.Order'),
        ),
    ]
