# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0026_auto_20180301_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='codeOfSample',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordersam', to='analyzes.Sample', verbose_name='Код образца'),
        ),
    ]
