# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0027_auto_20180303_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setanalyst',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst', to='analyzes.Order'),
        ),
    ]
