# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0028_auto_20180303_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setanalyst',
            old_name='Analyst',
            new_name='analyst',
        ),
    ]
