# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0029_auto_20180303_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executedDateTime',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата выполнения'),
        ),
    ]
