# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0032_auto_20180401_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executedDateTime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
    ]
