# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-01 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0033_auto_20180401_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='executedDateTime',
            new_name='executedDateTime2',
        ),
    ]
