# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-01 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzes', '0034_auto_20180402_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='executedDateTime2',
            new_name='executedDateTime',
        ),
    ]
